CREATE TABLE Alumno (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    mail VARCHAR(100) NOT NULL UNIQUE,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    contraseña VARCHAR(100) NOT NULL,
    limiteCursos INT NOT NULL,
    deuda DECIMAL(10,2) DEFAULT 0
);

CREATE TABLE Profesor (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    mail VARCHAR(100) NOT NULL UNIQUE,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    contraseña VARCHAR(100) NOT NULL,
    departamento VARCHAR(50)
);

CREATE TABLE Administrador (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    mail VARCHAR(100) NOT NULL UNIQUE,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    contraseña VARCHAR(100) NOT NULL,
    sector VARCHAR(50)
);

CREATE TABLE Curso (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    cupo INT NOT NULL,
    fechaInicio DATE NOT NULL,
    fechaFin DATE NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    fechaInicioDescuento DATE NOT NULL,
    fechaFinDescuento DATE NOT NULL,
    precioDescuento DECIMAL(10,2) NOT NULL,
    idProfesor INT NOT NULL,
    turno VARCHAR(50),
    cantidadParciales INT NOT NULL,
    notaAprobacion DOUBLE NOT NULL,
    notaPromocion DOUBLE NOT NULL,

    FOREIGN KEY (idProfesor) REFERENCES Profesor(id)
);

CREATE TABLE Inscripcion (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumnoId INT NOT NULL,
    cursoId INT NOT NULL,
    notaFinal DOUBLE,
    finalizada BOOLEAN DEFAULT FALSE,

    FOREIGN KEY (alumnoId) REFERENCES Alumno(id),
    FOREIGN KEY (cursoId) REFERENCES Curso(id)
);

CREATE TABLE NotaParcial (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcionId INT NOT NULL,
    nota DOUBLE NOT NULL,

    FOREIGN KEY (inscripcionId) REFERENCES Inscripcion(id)
);
